version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .

     # deploy the image
     - run: |         
         docker login --username=jorgemirandaneto@gmail.com --password=miranda130389 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/exemplo-teste/web
         docker push registry.heroku.com/exemplo-teste/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a exemplo-teste
